// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2-0kEi0KSwqR-_Mc7dUvdW06qJ2lxBiE',
    appId: '1:1047929231167:web:d8c09617a870318794e58a',
    messagingSenderId: '1047929231167',
    projectId: 'pulse-track-surgery',
    authDomain: 'pulse-track-surgery.firebaseapp.com',
    storageBucket: 'pulse-track-surgery.firebasestorage.app',
    measurementId: 'G-ZZRJLD6KPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN_3ag8PjcoKpzK0sslgNWqOPCyEuFgDc',
    appId: '1:1047929231167:android:66597ce8aa90d5c794e58a',
    messagingSenderId: '1047929231167',
    projectId: 'pulse-track-surgery',
    storageBucket: 'pulse-track-surgery.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnU6a4M4m6tT3eSBkv96dCVtp3539YP4U',
    appId: '1:1047929231167:ios:830adcdf1ce821dd94e58a',
    messagingSenderId: '1047929231167',
    projectId: 'pulse-track-surgery',
    storageBucket: 'pulse-track-surgery.firebasestorage.app',
    androidClientId: '1047929231167-2ojog9dtkao26lk63kmkn5qeu8n3hqte.apps.googleusercontent.com',
    iosClientId: '1047929231167-b2sb20bv22ifhavvvltr37ts1u1anjk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.pulse',
  );
}
